<template>
    <PhotoBanner></PhotoBanner>
    <SpacerProject></SpacerProject>
    <BrandSection></BrandSection>
    <SpacerProject></SpacerProject>
    <PortfolioFeatures></PortfolioFeatures>
    <SpacerProject></SpacerProject>
    <SignUp></SignUp>
</template>