<template>
    <div>
        <PhotoBanner></PhotoBanner>
        <SpacerProject></SpacerProject>
        <ListIndustries></ListIndustries>
        <SignUp></SignUp>
        <SpacerEnd></SpacerEnd>
    </div>
</template>